# Better one-liner formatting configuration
max_width = 200
use_small_heuristics = "Max"
fn_single_line = true
where_single_line = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
